#!/usr/bin/env python3
"""Build a binary Roblox Studio-ready place (.rbxl) with the REAL world embedded.

Merges assets/world/EggHeistWorld.rbxm (generated by tools/build_world.py)
with every .luau file under src/ (Rojo naming conventions) into ONE open-and-Play
place file: Egg-Heist.rbxl (repo root).

Merge strategy (no CFrame decoding required):
  - World INST/PROP bytes are copied VERBATIM (world referents 0..513 untouched).
  - New referents (514+) are assigned to services/folders/scripts only.
  - PRNT is re-encoded as: world pairs (EggHeist root re-parented under the new
    Workspace) + new pairs, then roundtrip-verified on every build.
  - Only fully-understood property encodings are emitted: String (0x01),
    Bool (0x02). Scripts use inline Source (never SharedString).
  - Header class/instance counts are patched; META/SSTR copied verbatim.

Usage: python3 tools/build_binary_place.py
"""
import struct
import sys
from pathlib import Path

import lz4.block

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
WORLD = ROOT / "assets" / "world" / "EggHeistWorld.rbxm"

sys.path.insert(0, str(ROOT / "tools"))
from inspect_rbxm import read_chunks, uninterleave, zigzag  # noqa: E402


# ----------------------------------------------------------------------------
# binary encoders (inverses of the validated decoders in inspect_rbxm.py)
# ----------------------------------------------------------------------------

def interleave(values):
    """u32 list -> byte-interleaved bytes (most-significant group first)."""
    n = len(values)
    groups = [bytearray(n) for _ in range(4)]
    for i, v in enumerate(values):
        v &= 0xFFFFFFFF
        groups[0][i] = (v >> 24) & 0xFF
        groups[1][i] = (v >> 16) & 0xFF
        groups[2][i] = (v >> 8) & 0xFF
        groups[3][i] = v & 0xFF
    return b"".join(bytes(g) for g in groups)


def _zz_encode(n):
    return ((n << 1) ^ (n >> 31)) & 0xFFFFFFFF if n >= 0 else ((-n * 2 - 1) & 0xFFFFFFFF)


def encode_deltas(ids):
    """Referent list -> interleaved cumulative-zigzag-delta bytes."""
    out = []
    prev = 0
    for ref in ids:
        out.append(_zz_encode(ref - prev) & 0xFFFFFFFF)
        prev = ref
    return interleave(out)


def encode_strings(values):
    """List of str/bytes -> inline string array (u32LE len + bytes each)."""
    out = bytearray()
    for v in values:
        b = v.encode("utf-8") if isinstance(v, str) else bytes(v)
        out += struct.pack("<I", len(b))
        out += b
    return bytes(out)


def frame_chunk(name, payload, compress=True):
    if compress:
        raw = lz4.block.compress(payload, store_size=False)
        # lz4.block.compress must roundtrip through the reader's decompress call
        assert lz4.block.decompress(raw, uncompressed_size=len(payload)) == payload
        clen, ulen = len(raw), len(payload)
    else:
        raw = payload
        clen, ulen = 0, len(payload)
    return name.encode("ascii") + struct.pack("<III", clen, ulen, 0) + raw


# ----------------------------------------------------------------------------
# src/ tree -> content plan (Rojo naming conventions; must agree with
# default.project.json so `rojo build` produces the same game)
# ----------------------------------------------------------------------------

class Node:
    def __init__(self, class_name, name, props=None):
        self.class_name = class_name
        self.name = name
        self.props = props or {}  # prop name -> ("s", str) | ("b", bool)
        self.children = []
        self.ref = None


def node_for_file(path):
    name = path.name
    source = path.read_text(encoding="utf-8")
    if name.endswith(".server.luau"):
        n = Node("Script", name[: -len(".server.luau")])
        n.props = {"Disabled": ("b", False), "Source": ("s", source)}
        return n
    if name.endswith(".client.luau"):
        n = Node("LocalScript", name[: -len(".client.luau")])
        n.props = {"Disabled": ("b", False), "Source": ("s", source)}
        return n
    if name.endswith(".luau"):
        n = Node("ModuleScript", name[: -len(".luau")])
        n.props = {"Source": ("s", source)}
        return n
    return None


def node_for_dir(path):
    folder_name = path.name
    children = []
    init_source = None
    init_class = None
    for child in sorted(path.iterdir(), key=lambda p: p.name):
        if child.is_file() and child.suffix == ".luau":
            if child.name in ("init.luau", "init.server.luau", "init.client.luau"):
                init_source = child.read_text(encoding="utf-8")
                if child.name == "init.server.luau":
                    init_class = "Script"
                elif child.name == "init.client.luau":
                    init_class = "LocalScript"
                else:
                    init_class = "ModuleScript"
            else:
                item = node_for_file(child)
                if item:
                    children.append(item)
        elif child.is_dir():
            children.append(node_for_dir(child))
    if init_class and init_source is not None:
        n = Node(init_class, folder_name)
        n.props = {"Source": ("s", init_source)}
        if init_class != "ModuleScript":
            n.props["Disabled"] = ("b", False)
        n.children = children
        return n
    n = Node("Folder", folder_name)
    n.children = children
    return n


def service_children(name):
    path = SRC / name
    if not path.is_dir():
        return []
    kids = []
    for child in sorted(path.iterdir(), key=lambda p: p.name):
        if child.is_dir():
            kids.append(node_for_dir(child))
        elif child.is_file() and child.suffix == ".luau":
            item = node_for_file(child)
            if item:
                kids.append(item)
    return kids


SERVICE_CLASSES = {
    "Workspace", "Lighting", "ReplicatedStorage", "ServerScriptService",
    "StarterPlayer", "StarterGui", "ServerStorage", "SoundService", "Teams",
}


def build_content():
    """Services list; matches default.project.json services exactly."""
    services = []
    workspace = Node("Workspace", "Workspace")
    # No spawn stub: the world (EggHeist/Map/Spawn/SpawnLocation, built by
    # tools/build_world.py) carries a complete Neutral spawn that
    # WorldService.EnsureSpawn reuses and snaps onto the plaza at boot.
    workspace.children = []
    workspace.children.extend(service_children("Workspace"))
    services.append(workspace)
    services.append(Node("Lighting", "Lighting"))
    rs = Node("ReplicatedStorage", "ReplicatedStorage")
    rs.children = service_children("ReplicatedStorage")
    services.append(rs)
    sss = Node("ServerScriptService", "ServerScriptService")
    sss.children = service_children("ServerScriptService")
    services.append(sss)
    sp = Node("StarterPlayer", "StarterPlayer")
    sps = Node("StarterPlayerScripts", "StarterPlayerScripts")
    spd = SRC / "StarterPlayer" / "StarterPlayerScripts"
    if spd.is_dir():
        for child in sorted(spd.iterdir(), key=lambda p: p.name):
            if child.is_dir():
                sps.children.append(node_for_dir(child))
            elif child.is_file() and child.suffix == ".luau":
                item = node_for_file(child)
                if item:
                    sps.children.append(item)
    scs = Node("StarterCharacterScripts", "StarterCharacterScripts")
    scd = SRC / "StarterPlayer" / "StarterCharacterScripts"
    if scd.is_dir():
        for child in sorted(scd.iterdir(), key=lambda p: p.name):
            if child.is_dir():
                scs.children.append(node_for_dir(child))
            elif child.is_file() and child.suffix == ".luau":
                item = node_for_file(child)
                if item:
                    scs.children.append(item)
    sp.children = [sps]
    if scs.children or scd.is_dir():
        sp.children.append(scs)
    services.append(sp)
    sg = Node("StarterGui", "StarterGui")
    sg.children = service_children("StarterGui")
    services.append(sg)
    ss = Node("ServerStorage", "ServerStorage")
    ss.children = service_children("ServerStorage")
    services.append(ss)
    services.append(Node("SoundService", "SoundService"))
    services.append(Node("Teams", "Teams"))
    return services


# ----------------------------------------------------------------------------
# merge
# ----------------------------------------------------------------------------

def parse_world(data):
    chunks = read_chunks(data)
    insts = []  # (cid, cname, isSvc, count, ids[])
    prnt = []  # (child, parent)
    meta = sstr = None
    prop_payloads = []
    for name, payload in chunks:
        if name == "META":
            meta = payload
        elif name == "SSTR":
            sstr = payload
        elif name == "INST":
            cid, nlen = struct.unpack("<II", payload[0:8])
            cname = payload[8:8 + nlen].decode()
            is_svc = payload[8 + nlen]
            pos = 8 + nlen + 1
            (count,) = struct.unpack("<I", payload[pos:pos + 4])
            raw = uninterleave(payload[pos + 4:pos + 4 + 4 * count], count)
            acc, ids = 0, []
            for v in raw:
                acc += zigzag(v)
                ids.append(acc)
            insts.append((cid, cname, is_svc, count, ids))
        elif name == "PROP":
            prop_payloads.append(payload)
        elif name == "PRNT":
            n = struct.unpack("<I", payload[1:5])[0]
            cs = uninterleave(payload[5:5 + 4 * n], n)
            ps = uninterleave(payload[5 + 4 * n:5 + 8 * n], n)
            ca = pa = 0
            for c, p in zip(cs, ps):
                ca += zigzag(c)
                pa += zigzag(p)
                prnt.append((ca, pa))
    return insts, prnt, meta, sstr, prop_payloads


def main():
    data = WORLD.read_bytes()
    header = bytearray(data[:32])
    w_classes, w_instances = struct.unpack("<II", header[16:24])
    insts, w_prnt, meta, sstr, w_props = parse_world(data)
    assert w_classes == len(insts), (w_classes, len(insts))
    assert w_instances == sum(c for _, _, _, c, _ in insts)
    world_ids = [i for _, _, _, _, ids in insts for i in ids]
    assert sorted(world_ids) == list(range(w_instances)), "world referents must be 0..N-1"
    assert sorted(c for c, _ in w_prnt) == list(range(w_instances)), "PRNT must cover all"

    # world EggHeist root -> re-parent under new Workspace
    world_root = [c for c, p in w_prnt if p == -1]
    assert len(world_root) == 1, world_root
    world_root = world_root[0]

    services = build_content()
    # assign referents (breadth-first per class grouping happens at emit)
    order = []
    def walk(n):
        order.append(n)
        for k in n.children:
            walk(k)
    for s in services:
        walk(s)
    next_ref = w_instances
    for n in order:
        n.ref = next_ref
        next_ref += 1
    my_count = len(order)

    # group by class (stable: first-seen class order)
    by_class = {}
    for n in order:
        by_class.setdefault(n.class_name, []).append(n)
    # Classes shared with the world (Folder) MERGE into the world's INST/PROP
    # chunks: the world's Folder PROPs are all defaults (empty Attributes,
    # zero Capabilities/DefinesCapabilities/IconTint/Tags, SourceAssetId=1
    # as 8-group-MSB-interleaved u64), so extending them replicates the
    # world's own bytes with zero encoding unknowns. Result: exactly one
    # INST per class, like Studio-saved files.
    world_by_class = {}
    for cid, cname, is_svc, count, ids in insts:
        world_by_class[cname] = (cid, count, ids)
    next_cid = max(cid for cid, _, _, _, _ in insts) + 1
    my_cids = {}   # my class -> cid (world cid when merged, else fresh)
    merged = {}    # world cid -> (world_ids, my_nodes) for merged classes
    for cname, nodes in by_class.items():
        if cname in world_by_class:
            cid, _, wids = world_by_class[cname]
            assert cname == "Folder", f"merge only implemented for Folder, not {cname}"
            my_cids[cname] = cid
            merged[cid] = (wids, nodes)
        else:
            my_cids[cname] = next_cid
            next_cid += 1

    fresh_classes = [c for c in by_class if my_cids[c] not in merged]
    out = bytearray()
    out += header[:16] + struct.pack("<II", w_classes + len(fresh_classes), w_instances + my_count) + header[24:32]

    # META + SSTR verbatim
    assert meta is not None and sstr is not None
    out += frame_chunk("META", meta)
    out += frame_chunk("SSTR", sstr)

    src_insts = {}
    for nm, p in read_chunks(data):
        if nm == "INST":
            cc, _nl = struct.unpack("<II", p[0:8])
            src_insts[cc] = p

    # world INST chunks verbatim (re-framed, same payload bytes),
    # except merged classes whose id arrays are extended with my refs
    for (cid, cname, is_svc, count, ids) in insts:
        if cid in merged:
            wids, my_nodes = merged[cid]
            assert ids == wids
            mine = sorted(n.ref for n in my_nodes)
            full = wids + mine
            payload = struct.pack("<II", cid, len(cname.encode())) + cname.encode() \
                + bytes([is_svc]) + struct.pack("<I", len(full)) + encode_deltas(full)
            # encoder validated against the world-only prefix first
            expect = struct.pack("<II", cid, len(cname.encode())) + cname.encode() \
                + bytes([is_svc]) + struct.pack("<I", count) + encode_deltas(ids)
            assert src_insts[cid] == expect, f"INST re-encode mismatch: {cname}"
            # and the extension decodes back exactly
            raw = uninterleave(payload[len(payload) - 4 * len(full):], len(full))
            acc, back = 0, []
            for v in raw:
                acc += zigzag(v)
                back.append(acc)
            assert back == full
            out += frame_chunk("INST", payload)
            continue
        payload = struct.pack("<II", cid, len(cname.encode())) + cname.encode() \
            + bytes([is_svc]) + struct.pack("<I", count) + encode_deltas(ids)
        # roundtrip check: re-encode must match the source payload exactly
        assert src_insts[cid] == payload, f"INST re-encode mismatch: {cname}"
        out += frame_chunk("INST", payload)

    # my INST chunks (fresh classes only; merged classes ride the world's)
    for cname in fresh_classes:
        nodes = by_class[cname]
        ids = sorted(n.ref for n in nodes)
        assert ids == [n.ref for n in nodes], "refs must already be ascending per class"
        is_service = cname in SERVICE_CLASSES
        payload = struct.pack("<II", my_cids[cname], len(cname.encode())) + cname.encode() \
            + bytes([1 if is_service else 0]) \
            + struct.pack("<I", len(ids)) + encode_deltas(ids)
        if is_service:
            # Service marker bytes ("isServiceRooted"): Studio REQUIRES one
            # 0x01 byte per instance after the referent array when the
            # service flag is set (see rbx_binary serializer/state.rs
            # serialize_instances, and any Studio-saved place: service
            # INST payloads end with 01). Missing bytes = Studio fails to
            # open the place ("MemoryInputStream::read offset is out of
            # bounds ... isServiceRooted ... chunk#[INST]").
            payload += bytes([1]) * len(ids)
        out += frame_chunk("INST", payload)

    def extend_folder_prop(prop_name, ptype, world_body, wcount, my_nodes_sorted):
        """Extend one world Folder PROP body with my folders' values.

        Every extension replicates the world's own default bytes; each
        assumption is asserted against the world body before extending."""
        m = len(my_nodes_sorted)
        if prop_name == "Name":
            assert ptype == 0x01
            return world_body + encode_strings([n.name for n in my_nodes_sorted])
        if prop_name == "AttributesSerialize":
            assert ptype == 0x01 and world_body == b"\x00\x00\x00\x00" * wcount
            return world_body + b"\x00\x00\x00\x00" * m
        if prop_name == "DefinesCapabilities":
            assert ptype == 0x02 and world_body == bytes(wcount)
            return world_body + bytes(m)
        if prop_name == "Capabilities":
            assert world_body == bytes(8 * wcount), "Capabilities must be all-zero u64"
            return world_body + bytes(8 * m)
        if prop_name == "IconTint":
            assert world_body == bytes(12 * wcount), "IconTint must be all-zero"
            return world_body + bytes(12 * m)
        if prop_name == "Tags":
            assert world_body == bytes(4 * wcount), "Tags must be all-empty"
            return world_body + bytes(4 * m)
        if prop_name == "SourceAssetId":
            # 8-group MSB-interleaved u64; world's folders are all == 1
            assert len(world_body) == 8 * wcount
            groups = [world_body[g * wcount:(g + 1) * wcount] for g in range(8)]
            for i in range(wcount):
                v = 0
                for g in range(8):
                    v |= groups[g][i] << (8 * (7 - g))
                assert v == 1, f"SourceAssetId[{i}] != 1: {v}"
            out = bytearray()
            for g in range(8):
                out += groups[g] + (bytes([1]) * m if g == 7 else bytes(m))
            return bytes(out)
        raise AssertionError(f"unhandled Folder prop: {prop_name} (0x{ptype:02x})")

    # world PROP chunks verbatim, except merged classes (extended in place,
    # keeping world order)
    for p in w_props:
        cid, nlen = struct.unpack("<II", p[0:8])
        if cid in merged:
            wids, my_nodes = merged[cid]
            my_sorted = sorted(my_nodes, key=lambda n: n.ref)
            assert all(not n.props for n in my_nodes), "merged folders must carry no extra props"
            pn = p[8:8 + nlen].decode()
            new_body = extend_folder_prop(pn, p[8 + nlen], p[8 + nlen + 1:], len(wids), my_sorted)
            out += frame_chunk("PROP", p[:8 + nlen + 1] + new_body)
        else:
            out += frame_chunk("PROP", p)

    # my PROP chunks: Name for every fresh class; Source/Disabled/others per node
    for cname in fresh_classes:
        nodes = by_class[cname]
        cid = my_cids[cname]
        # Name (0x01 String, inline)
        payload = struct.pack("<II", cid, 4) + b"Name" + bytes([0x01]) \
            + encode_strings([n.name for n in nodes])
        out += frame_chunk("PROP", payload)
        # union of extra props across nodes of this class (sorted for determinism)
        extra = sorted({k for n in nodes for k in n.props})
        for prop in extra:
            kinds = {n.props[prop][0] for n in nodes if prop in n.props}
            assert len(kinds) == 1, (cname, prop, kinds)
            kind = kinds.pop()
            if kind == "s":
                body = encode_strings([n.props[prop][1] if prop in n.props else "" for n in nodes])
                ptype = 0x01
            elif kind == "b":
                body = bytes([1 if (n.props.get(prop, ("b", False))[1]) else 0 for n in nodes])
                ptype = 0x02
            else:
                raise AssertionError(kind)
            pb = prop.encode()
            payload = struct.pack("<II", cid, len(pb)) + pb + bytes([ptype]) + body
            out += frame_chunk("PROP", payload)

    # PRNT: world pairs (root re-parented) + mine. The world's
    # SpawnLocation also rides at Workspace top level: HealthService only
    # accepts a top-level spawn, and EnsureSpawn/Studio find it there first.
    workspace_ref = [n.ref for n in order if n.class_name == "Workspace"][0]
    spawn_refs = set(world_by_class.get("SpawnLocation", (None, 0, []))[2])
    pairs = [(c, workspace_ref if (p == -1 or c in spawn_refs) else p)
             for c, p in w_prnt]
    def parent_ref(parent, kids):
        for k in kids:
            pairs.append((k.ref, parent.ref))
            parent_ref(k, kids=k.children)
    for s in services:
        pairs.append((s.ref, -1))
        parent_ref(s, s.children)
    assert len(pairs) == w_instances + my_count
    assert sorted(c for c, _ in pairs) == list(range(w_instances + my_count))
    prnt_payload = bytes([0]) + struct.pack("<I", len(pairs)) \
        + encode_deltas([c for c, _ in pairs]) + encode_deltas([p for _, p in pairs])
    out += frame_chunk("PRNT", prnt_payload)

    # Studio footer: END chunk, uncompressed 9-byte `</roblox>` payload
    out += b"END\x00" + struct.pack("<III", 0, 9, 0) + b"</roblox>"

    out_path = ROOT / "Egg-Heist.rbxl"
    out_path.write_bytes(bytes(out))
    print(f"Wrote {out_path} ({len(out):,} bytes)")
    print(f"  world: {w_classes} classes, {w_instances} instances "
          f"(Folder class merged, all other bytes verbatim)")
    print(f"  added: {len(fresh_classes)} classes, {my_count} instances "
          f"({sum(1 for n in order if n.class_name in ('Script','LocalScript','ModuleScript'))} scripts)")

    # ---- verify: re-parse the output and check everything ----
    verify(out_path, data, services, order, w_prnt, world_root, workspace_ref, merged)
    return 0


def verify(out_path, world_data, services, order, w_prnt, world_root, workspace_ref, merged):
    data = out_path.read_bytes()
    assert data[:8] == b"<roblox!"
    assert data[-25:] == b"END\x00" + struct.pack("<III", 0, 9, 0) + b"</roblox>"
    w_classes, w_instances = struct.unpack("<II", world_data[16:24])
    o_classes, o_instances = struct.unpack("<II", data[16:24])
    assert o_instances == w_instances + len(order), (o_instances, w_instances, len(order))
    chunks = read_chunks(data)
    kinds = [k for k, _ in chunks]
    assert kinds[0] == "META" and kinds[1] == "SSTR" and kinds[-1] == "PRNT", kinds[:3] + kinds[-2:]
    # exactly one INST per class (like Studio files)
    seen_classes = []
    for k, p in chunks:
        if k != "INST":
            continue
        _cid, nlen = struct.unpack("<II", p[0:8])
        seen_classes.append(p[8:8 + nlen].decode())
    assert len(seen_classes) == len(set(seen_classes)) == o_classes, seen_classes
    # world PROP payloads byte-identical, except merged classes (validated
    # by decoding: world values intact + my appended values correct)
    w_props = [p for k, p in read_chunks(world_data) if k == "PROP"]
    o_props = [p for k, p in chunks if k == "PROP"]
    assert len(o_props) >= len(w_props)
    sys.path.insert(0, str(ROOT / "tools"))
    from inspect_rbxm import parse_strings as _parse_strings
    n_verbatim = 0
    for wp, op in zip(w_props, o_props):
        cid, _n = struct.unpack("<II", wp[0:8])
        if cid not in merged:
            assert op == wp, "world PROP bytes must be verbatim"
            n_verbatim += 1
            continue
        wids, my_nodes = merged[cid]
        my_sorted = sorted(my_nodes, key=lambda n: n.ref)
        wcount, mcount = len(wids), len(my_sorted)
        _wn, _wnl = struct.unpack("<II", wp[0:8])
        _on, _onl = struct.unpack("<II", op[0:8])
        assert wp[8:8 + _wnl] == op[8:8 + _onl], "merged PROP name must match"
        assert wp[8 + _wnl] == op[8 + _onl], "merged PROP type must match"
        pn = wp[8:8 + _wnl].decode()
        wb, ob = wp[8 + _wnl + 1:], op[8 + _onl + 1:]
        if pn == "Name":
            wnames = _parse_strings(wb, wcount)
            onames = _parse_strings(ob, wcount + mcount)
            assert onames[:wcount] == wnames, "world Folder names must be intact"
            assert onames[wcount:] == [n.name for n in my_sorted], "my folder names appended"
        elif pn in ("AttributesSerialize",):
            assert _parse_strings(ob, wcount + mcount) == [""] * (wcount + mcount)
        elif pn == "DefinesCapabilities":
            assert ob == bytes(wcount + mcount)
        elif pn == "Capabilities":
            assert ob == bytes(8 * (wcount + mcount))
        elif pn == "IconTint":
            assert ob == bytes(12 * (wcount + mcount))
        elif pn == "Tags":
            assert ob == bytes(4 * (wcount + mcount))
        elif pn == "SourceAssetId":
            assert len(ob) == 8 * (wcount + mcount)
            nn = wcount + mcount
            for i in range(nn):
                v = 0
                for g in range(8):
                    v |= ob[g * nn + i] << (8 * (7 - g))
                assert v == 1, f"SourceAssetId[{i}] != 1"
        else:
            raise AssertionError(f"unexpected merged PROP: {pn}")
    # PRNT prefix == world pairs with root re-parented
    o_prnt = []
    for k, p in chunks:
        if k != "PRNT":
            continue
        n = struct.unpack("<I", p[1:5])[0]
        cs = uninterleave(p[5:5 + 4 * n], n)
        ps = uninterleave(p[5 + 4 * n:5 + 8 * n], n)
        ca = pa = 0
        for c, q in zip(cs, ps):
            ca += zigzag(c)
            pa += zigzag(q)
            o_prnt.append((ca, pa))
    # world's SpawnLocation rides at Workspace top level (see main)
    w_spawn = set()
    for k, p in read_chunks(world_data):
        if k != "INST":
            continue
        _cc, _nl = struct.unpack("<II", p[0:8])
        if p[8:8 + _nl].decode() == "SpawnLocation":
            pos = 8 + _nl + 1
            (count,) = struct.unpack("<I", p[pos:pos + 4])
            acc = 0
            for v in uninterleave(p[pos + 4:pos + 4 + 4 * count], count):
                acc += zigzag(v)
                w_spawn.add(acc)
    assert len(w_spawn) == 1, w_spawn
    expect_head = [(c, workspace_ref if (q == -1 or c in w_spawn) else q)
                   for c, q in w_prnt]
    assert o_prnt[:len(expect_head)] == expect_head, "PRNT world prefix mismatch"
    # Name + Source props decode; sources match disk
    inst_ids = {}
    n_service_markers = 0
    for k, p in chunks:
        if k != "INST":
            continue
        cid, nlen = struct.unpack("<II", p[0:8])
        is_svc = p[8 + nlen]
        pos = 8 + nlen + 1
        (count,) = struct.unpack("<I", p[pos:pos + 4])
        # service INSTs must carry the trailing 0x01 marker per instance
        # (Studio refuses to open the place without them)
        expect_len = pos + 4 + 4 * count + (count if is_svc else 0)
        assert len(p) == expect_len, f"INST {cid} len {len(p)} != {expect_len}"
        if is_svc:
            assert p[pos + 4 + 4 * count:] == bytes([1]) * count
            n_service_markers += count
        raw = uninterleave(p[pos + 4:pos + 4 + 4 * count], count)
        acc, ids = 0, []
        for v in raw:
            acc += zigzag(v)
            ids.append(acc)
        inst_ids[cid] = ids
    ref2name = {}
    for k, p in chunks:
        if k != "PROP":
            continue
        cid, nlen = struct.unpack("<II", p[0:8])
        if p[8:8 + nlen] != b"Name":
            continue
        body = p[8 + nlen + 1:]
        pos = 0
        for i, ref in enumerate(inst_ids[cid]):
            (ln,) = struct.unpack("<I", body[pos:pos + 4])
            pos += 4
            ref2name[ref] = body[pos:pos + ln].decode()
            pos += ln
    for n in order:
        assert ref2name[n.ref] == n.name, (n.ref, ref2name.get(n.ref), n.name)
    n_src = 0
    for k, p in chunks:
        if k != "PROP":
            continue
        cid, nlen = struct.unpack("<II", p[0:8])
        if p[8:8 + nlen] != b"Source":
            continue
        body = p[8 + nlen + 1:]
        pos = 0
        for ref in inst_ids[cid]:
            (ln,) = struct.unpack("<I", body[pos:pos + 4])
            pos += 4
            src = body[pos:pos + ln].decode()
            pos += ln
            node = [x for x in order if x.ref == ref][0]
            assert src == node.props["Source"][1], f"Source mismatch: {node.name}"
            n_src += 1
    n_scripts = sum(1 for n in order if "Source" in n.props)
    assert n_src == n_scripts, (n_src, n_scripts)
    n_merged_names = sum(1 for n in order if n.ref in ref2name and n.class_name == "Folder")
    print(f"  verify OK: {n_verbatim} world PROPs verbatim, "
          f"{len(w_props) - n_verbatim} Folder PROPs extended, "
          f"{len(expect_head)} world PRNT pairs re-parented, "
          f"{len(order)} names ({n_merged_names} merged folders) + "
          f"{n_src} sources roundtrip-clean; one INST per class; "
          f"{n_service_markers} service markers")


if __name__ == "__main__":
    sys.exit(main())
